<a href="https://colab.research.google.com/github/YueunKim/Kriss_colab/blob/master/3_AutoGrad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#3, p.13
import torch
x = torch.tensor([1., 2.])
y = torch.tensor([4., 5.])
z = torch.tensor([7., 3.])
x.requires_grad

False

In [2]:
(x + y).requires_grad

False

In [3]:
z.requires_grad = True
(x + z).requires_grad

True

In [4]:
import torch
a, b = torch.rand((2,2)), torch.rand((2,2))
print("a: {}\n, b: {} \n".format(a, b))

var1 = torch.sum(torch.abs((a * b)), 1)
print("L1 Distance is : ", var1)

var2 = torch.norm(((a * b)), 1, -1)
print("Torch NORM L1 Distance is : ", var2)

var3 = torch.sum(((a * b)) ** 2, 1).sqrt()
print("L2 SDistance is : ", var3)

var4 = torch.norm(((a * b)), 2, -1)
print("Torch NORM L2 Distance is : ", var4)

a: tensor([[0.9096, 0.9174],
        [0.3563, 0.3930]])
, b: tensor([[0.2491, 0.4702],
        [0.6783, 0.6028]]) 

L1 Distance is :  tensor([0.6580, 0.4786])
Torch NORM L1 Distance is :  tensor([0.6580, 0.4786])
L2 SDistance is :  tensor([0.4872, 0.3384])
Torch NORM L2 Distance is :  tensor([0.4872, 0.3384])


In [5]:
#3, p.16
x = torch.tensor([-3., 2., 5.]).requires_grad_()
u = x.pow(3).sum()
print("x.grad:{}\n u.backward:{}\n x.grad:{}\n".format(x.grad, u.backward(), x.grad))

x.grad:None
 u.backward:None
 x.grad:tensor([27., 12., 75.])



In [6]:
#3, p.21
w1 = torch.rand(20, 10).requires_grad_()
b1 = torch.rand(20).requires_grad_()
w2 = torch.rand(5, 20).requires_grad_()
b2 = torch.rand(5).requires_grad_()
print('w1:{} \n, b1:{} \n, w2:{} \n, b2:{} \n'.format(w1, b1, w2, b2))

x = torch.rand(10)
h = torch.tanh(w1 @ x + b1)
y = torch.tanh(w2 @ h + b2)
print('x:{} \n, h:{} \n, y:{} \n'.format(x, h, y))

target = torch.rand(5)
loss = (y - target).pow(2).mean()
print('target: {}\n, loss: {}\n'.format( target, loss))

w1:tensor([[0.2438, 0.2192, 0.2099, 0.4254, 0.4836, 0.4383, 0.5023, 0.0505, 0.4520,
         0.5421],
        [0.1613, 0.6693, 0.0581, 0.9759, 0.2089, 0.2755, 0.7721, 0.3915, 0.6880,
         0.7741],
        [0.6675, 0.2729, 0.6611, 0.2859, 0.7660, 0.5485, 0.6604, 0.0780, 0.3108,
         0.5777],
        [0.6078, 0.2387, 0.8852, 0.8101, 0.8601, 0.7025, 0.7041, 0.0924, 0.9289,
         0.4318],
        [0.6175, 0.2457, 0.0445, 0.5730, 0.3299, 0.1900, 0.1962, 0.0935, 0.1735,
         0.7486],
        [0.1867, 0.7411, 0.6782, 0.6259, 0.7114, 0.1523, 0.6799, 0.2032, 0.7471,
         0.2332],
        [0.5244, 0.1238, 0.4171, 0.6089, 0.3961, 0.6099, 0.0103, 0.4071, 0.2423,
         0.6791],
        [0.5749, 0.1897, 0.9231, 0.8840, 0.2795, 0.6557, 0.2769, 0.0350, 0.6572,
         0.1030],
        [0.8459, 0.4087, 0.0504, 0.3173, 0.8814, 0.9572, 0.0065, 0.0771, 0.3666,
         0.6724],
        [0.8572, 0.0736, 0.8769, 0.2313, 0.6769, 0.9435, 0.4397, 0.8888, 0.7743,
         0.9753],
       

In [7]:
#3, p.22
w = torch.rand(3, 10, 10).requires_grad_()

def blah(k, x):
    for i in range(k):
        x = torch.tanh(w[i] @ x)
    return x

u = blah(1, torch.rand(10))
v = blah(3, torch.rand(10))
q = u.dot(v)
print('w: {} \n, u: {}\n, v: {}\n q: {}\n'.format(w, u, v, q))

w: tensor([[[0.4016, 0.5643, 0.8041, 0.0343, 0.9006, 0.6548, 0.7330, 0.3341,
          0.0540, 0.0440],
         [0.6942, 0.0375, 0.4551, 0.3140, 0.6910, 0.8053, 0.6692, 0.7501,
          0.4711, 0.2952],
         [0.5780, 0.1283, 0.3007, 0.1687, 0.0269, 0.9150, 0.5099, 0.0366,
          0.6634, 0.4998],
         [0.2787, 0.4167, 0.7726, 0.7636, 0.8691, 0.6200, 0.2659, 0.0664,
          0.7403, 0.5818],
         [0.2650, 0.4073, 0.4706, 0.7319, 0.8563, 0.5405, 0.2593, 0.0215,
          0.3746, 0.4530],
         [0.2640, 0.2602, 0.3294, 0.1234, 0.5493, 0.6062, 0.3205, 0.1389,
          0.5221, 0.3786],
         [0.4305, 0.7185, 0.9859, 0.8080, 0.9135, 0.6430, 0.0735, 0.5485,
          0.2739, 0.8506],
         [0.5572, 0.5658, 0.0013, 0.4289, 0.3149, 0.8674, 0.7013, 0.6257,
          0.9080, 0.7448],
         [0.7563, 0.3855, 0.7714, 0.7064, 0.2360, 0.1531, 0.9290, 0.5205,
          0.5772, 0.8378],
         [0.7318, 0.1809, 0.0613, 0.7885, 0.2985, 0.7038, 0.6526, 0.2346,
          0.74

In [8]:
a = torch.tensor([1, 3])
b = torch.tensor([2, 2])
c = a.dot(b)
c

tensor(8)

In [9]:
t = torch.tensor([1., 2., 4.]).requires_grad_()
u = torch.tensor([10., 20.]).requires_grad_()
a = t.pow(2).sum() + u.log().sum()
r = torch.autograd.grad(a, (t, u))
print("t:{} \n u:{} \n a:{} \n r = {} \n".format(t, u, a, r))

t:tensor([1., 2., 4.], requires_grad=True) 
 u:tensor([10., 20.], requires_grad=True) 
 a:26.298316955566406 
 r = (tensor([2., 4., 8.]), tensor([0.1000, 0.0500])) 



In [10]:
s = u.log().sum()
torch.autograd.grad(s, u)

(tensor([0.1000, 0.0500]),)

In [11]:
w = torch.rand(3, 10).requires_grad_()
x = torch.rand(10)
y = w @ x
print('w: {},\n x: {},\n y: {}'.format(w, x, y))

w: tensor([[0.9088, 0.0129, 0.2507, 0.8754, 0.3919, 0.7446, 0.4900, 0.6081, 0.1300,
         0.6680],
        [0.5865, 0.0103, 0.7796, 0.4534, 0.2015, 0.1284, 0.2013, 0.6560, 0.4843,
         0.6856],
        [0.6809, 0.3889, 0.9415, 0.9398, 0.2798, 0.5233, 0.7171, 0.2097, 0.7541,
         0.0031]], requires_grad=True),
 x: tensor([0.3153, 0.0828, 0.0921, 0.3796, 0.8560, 0.9496, 0.1313, 0.7212, 0.9424,
        0.1953]),
 y: tensor([2.4414, 1.8140, 2.3834], grad_fn=<MvBackward>)


In [12]:
w1 = torch.rand(5, 5).requires_grad_()
w2 = torch.rand(5, 5).requires_grad_()
x = torch.empty(5).normal_()
print("w1:{} \n w2: {} \n x : {}\n".format(w1, w2, x))

x0 = x
x1 = w1 @ x0
x2 = x0 + w2 @ x1
x3 = w1 @ (x1 + x2)

q = x3.norm()

q.backward()

w1:tensor([[0.5169, 0.1589, 0.6770, 0.3035, 0.1148],
        [0.0027, 0.4072, 0.3252, 0.8551, 0.0736],
        [0.8257, 0.3258, 0.8955, 0.1060, 0.8489],
        [0.8150, 0.8017, 0.9622, 0.7748, 0.8278],
        [0.9394, 0.8869, 0.3062, 0.2317, 0.0723]], requires_grad=True) 
 w2: tensor([[0.3676, 0.6446, 0.0566, 0.9806, 0.0760],
        [0.4358, 0.9686, 0.4406, 0.8527, 0.8919],
        [0.0031, 0.8759, 0.7321, 0.4866, 0.0521],
        [0.6613, 0.2223, 0.1640, 0.0271, 0.4499],
        [0.3262, 0.4558, 0.0912, 0.8121, 0.2938]], requires_grad=True) 
 x : tensor([-0.3104, -1.9273,  1.0491,  0.0967, -0.2798])



In [13]:
x = torch.tensor([1.0, -2.0, 3.0, -4.0]).requires_grad_()
a = x.abs()
s = a.sum()
s



tensor(10., grad_fn=<SumBackward0>)

In [14]:
s.grad_fn.next_functions

((<AbsBackward at 0x7f94cb49fa90>, 0),)

In [15]:
x = torch.tensor([1., 2., 2.]).requires_grad_()
q = x.norm()
q

tensor(3., grad_fn=<CopyBackwards>)

In [16]:
#3, p.24
x = torch.rand(784)
w = torch.empty(10, 784).normal_(0, 1e-3).requires_grad_()
b = torch.empty(10).normal_(0, 1e-3).requires_grad_()
y = torch.rand(10)
eta = 0.01

for k in range(10001):
    y_hat = x @ w.t() + b
    loss = (y_hat - y).pow(2).mean()

    w.grad, b.grad = None, None
    loss.backward()

    with torch.no_grad():
        w -= eta * w.grad
        b -= eta * b.grad

In [17]:
#3, p.26
a = torch.tensor( 0.5).requires_grad_()
b = torch.tensor(-0.5).requires_grad_()
for k in range(100):
    l = (a - 1)**2 + (b + 1)**2 + (a - b)**2
    ga, gb = torch.autograd.grad(l, (a, b))
    with torch.no_grad():
        a -= eta * ga
        b -= eta * gb
print('%.06f' % a.item(), '%.06f' % b.item())

0.333676 -0.333676


In [18]:
#3, p.27
a = torch.tensor( 0.5).requires_grad_()
b = torch.tensor(-0.5).requires_grad_()
for k in range(100):
    l = (a - 1)**2 + (b + 1)**2 + (a.detach() - b)**2
    ga, gb = torch.autograd.grad(l, (a, b))
    with torch.no_grad():
        a -= eta * ga
        b -= eta * gb
print('%.06f' % a.item(), '%.06f' % b.item())

0.933690 -0.066310


In [19]:
#3, p.28
x = torch.tensor([1., 2., 3.]).requires_grad_()
phi = x.pow(2).sum()
g1, = torch.autograd.grad(phi, x, create_graph = True)
g1

tensor([2., 4., 6.], grad_fn=<MulBackward0>)

In [20]:
#3, p.28
psi = g1[0].exp() - g1[2].exp()
g2, = torch.autograd.grad(psi, x)
g2

tensor([  14.7781,    0.0000, -806.8576])

In [21]:
#3, p.29
x = torch.tensor([1., 2., 3.]).requires_grad_()
y = x.sin()
print('y : {}'.format(y))
l = y.sum()
l.backward()
print('l=sum(x.sin()), l : {}'.format(l))
y = x.sin()
y += 1
print('y : {}'.format(y))
l = y.sum()
l.backward()
print('l=sum(x.sin()+1), l : {}'.format(l))
y = x.sin()
y *=y
print('y : {}'.format(y))
l = y.sum()
print('l=sum(x.sin()*x.sin()), l : {}'.format(l))
l.backward()
print('l : {}'.format(l))

y : tensor([0.8415, 0.9093, 0.1411], grad_fn=<SinBackward>)
l=sum(x.sin()), l : 1.8918883800506592
y : tensor([1.8415, 1.9093, 1.1411], grad_fn=<AddBackward0>)
l=sum(x.sin()+1), l : 4.891888618469238
y : tensor([0.7081, 0.8268, 0.0199], grad_fn=<MulBackward0>)
l=sum(x.sin()*x.sin()), l : 1.5548100471496582


RuntimeError: ignored