<a href="https://colab.research.google.com/github/YueunKim/Kriss_colab/blob/master/torch_tensor1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
x = torch.empty(2, 5)
x.size()

torch.Size([2, 5])

In [2]:
x.fill_(1.125)

tensor([[1.1250, 1.1250, 1.1250, 1.1250, 1.1250],
        [1.1250, 1.1250, 1.1250, 1.1250, 1.1250]])

In [3]:
x.mean()

tensor(1.1250)

In [4]:
x.std()

tensor(0.)

In [5]:
x.sum()

tensor(11.2500)

In [6]:
x.sum().item()

11.25

In [7]:
x = torch.tensor([[11., 12., 13.], [21., 22., 23.]])
x[1, 2]

tensor(23.)

In [8]:
x = torch.tensor([10., 20., 30.])
y = torch.tensor([11., 21., 31.])
x + y

tensor([21., 41., 61.])

In [9]:
x * y

tensor([110., 420., 930.])

In [10]:
x ** 2

tensor([100., 400., 900.])

In [11]:
m = torch.tensor([[0., 0., 3.], [0., 2., 0.],[1., 0., 0.]])

In [12]:
m.mv(x) #torch.mv(m, x) matrix x vec computation

tensor([90., 40., 10.])

In [13]:
torch.mv(m, x)

tensor([90., 40., 10.])

In [14]:
m@x

tensor([90., 40., 10.])

In [15]:
x = torch.empty(2, 4).random_(10)
x

tensor([[5., 0., 5., 4.],
        [8., 9., 1., 6.]])

In [16]:
x[0]

tensor([5., 0., 5., 4.])

In [17]:
x[0, :]

tensor([5., 0., 5., 4.])

In [18]:
x[:, 0]

tensor([5., 8.])

In [19]:
x[:, 1:3]

tensor([[0., 5.],
        [9., 1.]])

In [20]:
x[:, 1:3] = -1

In [21]:
x

tensor([[ 5., -1., -1.,  4.],
        [ 8., -1., -1.,  6.]])

In [22]:
y= torch.empty(3).normal_()

In [23]:
y

tensor([-0.8573,  1.0642,  2.0571])

In [24]:
m = torch.empty(3, 3).normal_(mean=0, std=1.0)
m

tensor([[-0.3891,  0.1026,  1.4472],
        [-1.9104, -0.2225, -0.8143],
        [-1.7848,  0.8519, -1.4503]])

In [25]:
q, _ = torch.lstsq(y, m)

In [26]:
q, _ = torch.lstsq(y, m)

In [27]:
torch.mm(m, q)

tensor([[-0.8573],
        [ 1.0642],
        [ 2.0571]])

In [28]:
a = torch.randn(5, 3)
a

tensor([[ 1.3502, -1.1283,  0.8221],
        [ 0.4627, -0.9424, -0.0813],
        [-0.5206, -1.6937,  0.4280],
        [ 1.7513, -1.4765,  0.3778],
        [ 0.7987, -1.1725, -0.2113]])

In [29]:
u, s, v = torch.svd(a)
u

tensor([[-0.5204, -0.2387, -0.6293],
        [-0.2808,  0.1193,  0.3794],
        [-0.3108,  0.9086, -0.2144],
        [-0.6395, -0.3196,  0.0691],
        [-0.3805,  0.0335,  0.6398]])

In [30]:
s

tensor([3.5413, 1.5890, 0.7645])

In [31]:
v

tensor([[-0.5915, -0.8012,  0.0908],
        [ 0.7818, -0.5974, -0.1787],
        [-0.1974,  0.0347, -0.9797]])

In [32]:
a = torch.empty(3, 3).uniform_(0, 1)
print(a)
b = torch.bernoulli(a)
print(b)

tensor([[0.8705, 0.6893, 0.3213],
        [0.0416, 0.1726, 0.4503],
        [0.5812, 0.8393, 0.9518]])
tensor([[1., 1., 0.],
        [0., 0., 0.],
        [0., 1., 1.]])


In [33]:
c = torch.cos(a)
c

tensor([[0.6445, 0.7717, 0.9488],
        [0.9991, 0.9851, 0.9003],
        [0.8358, 0.6680, 0.5802]])

In [34]:
x = torch.tensor([[1, 3, 0], [2, 4, 6]])
y = x.narrow(1, 1, 2)
y

tensor([[3, 0],
        [4, 6]])